---
title: "Moquet automatisation floraison"
author: "B. Maranget"
date: "01/06/2021"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```



# Objet

Il s'agit de cartographie en aplat à partir d'une date spécifique.

# librairies

```{r}
library(sf)
```


# les données

```{r}
data <- read.csv2("../data/dataMoquet.csv",stringsAsFactors = F)
chemin <-  "d:/OneDrive - ARVALIS - Institut du végétal/beaCarto/data sauve/"
nomfic <- paste0(chemin, "SEGMENTS_MFV8_L93.shp")
segment <- st_read(nomfic, quiet = T, stringsAsFactors = F)
```

# calcul date

TODO faire le calcul dans R

```{r}
dateRec <- as.numeric(as.Date(as.character("10/08/2021"),format = "%d/%m/%Y"))
data$diff10Aout <- as.numeric(dataRec - data$Date_rec)

```

# jointure

```{r}
str(data)
str(segment)
names(data)[1]<- "CODE_SEGMF"
jointure <- merge(segment, data, by = "CODE_SEGMF")
class(jointure)
plot(jointure$geometry)
```




