---
title: "Abris bus version 2025"
author: "B. Maranget"
date: "25/11/2025"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

spatialisation du fichier pour envoi au prestataire poubelle de flux.




# Environnement


## Librairies


```{r , eval=TRUE}
library(leaflet)
library(leafpop)
library(sf)
library(mapsf)
```


## Chemins


```{r}
chemin <-"C:/Users/bmaranget/Documents/03_SIG/03_03_Data/08_VOIRIE/mobilierUrbain/"
chPH <- "C:/Users/bmaranget/Documents/03_SIG/03_03_Data/05_PHOTOS/parc/"
```



## Données


```{r}
data <- read.csv("../data/abriBUS.csv")
data$Latitude
data <- st_as_sf(data, coords = c("Longitude", "Latitude"), crs = 4326)
mf_map(data)
st_write(data, "../data/mobPublicitaire.gpkg", "abriBUS", delete_Layer = T)
```










