---
title: "Antenne relais"
author: "B. Maranget"
date: "18/12/2024"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Récupération de la donnée opendata sur Bondy

https://data.anfr.fr/visualisation/table/?id=observatoire_2g_3g_4g&sort=adr_nm_cp&q=93140&location=11,48.98945,2.60719&dataChart=eyJxdWVyaWVzIjpbeyJjb25maWciOnsiZGF0YXNldCI6Im9ic2VydmF0b2lyZV8yZ18zZ180ZyIsIm9wdGlvbnMiOnsiaWQiOiJvYnNlcnZhdG9pcmVfMmdfM2dfNGcifX0sImNoYXJ0cyI6W3siYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiQVZHIiwieUF4aXMiOiJpZCIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoiZGF0ZV9tYWoiLCJtYXhwb2ludHMiOiIiLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiJ9XSwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZX0%3D

ANFR agence nationale des fréquences




# Environnement


## Librairies


```{r , eval=TRUE}
library(sf)
library(mapsf)
```


## Chemins


```{r}
chemin <- "C:/Users/bmaranget/Documents/03_SIG/03_03_Data/25_DEV_DURABLE/"
```



# Données



```{r}
antenne <- st_read(paste0(chemin,"antenneRelais.gpkg"))

```

# Agregation

## Par type de fréquence

```{r}
# filtre sur le 5 G
prop.table(table(antenne$generation))*100

antenne5G <- antenne [antenne$generation == '5G',]
antenne4G <- antenne [antenne$generation == '4G',]
```


```{r}
data <- antenne4G
agg <- aggregate(data [, c("adr_lb_add1","geom")], by=list(data$adr_lb_add1,  data$adm_lb_nom), length)
agg <- st_jitter(agg)
names(agg)[1:3]  <- c("Adresse", "Fournisseur", "nb")
hist(agg$nb)
st_write(agg, "../data/antenneRelais.gpkg", "agg4G", delete_layer = T)
summary(agg$nb)
length(agg$nb)
sum(agg$nb)
```


## Par antenne

En vue de créer une carte de densité pondérée par le nb d'antennes sur chaque point.

```{r}
data <- antenne
agg <- aggregate(data [, c("adr_lb_add1","geom")], by=list(data$adr_lb_add1), length)
names(agg)[1:2]  <- c("Adresse",  "nb")
hist(agg$nb)

```


# Densité


## Grille

Aire couverte par les antennes

```{r}
agg <- st_transform(agg, 2154)
enveloppe <- st_convex_hull(st_union(agg))
mf_map(enveloppe)
aire <- st_area(enveloppe)
aire
```


```{r}
grid <- st_make_grid(x = agg, cellsize = 200)
grid <- st_sf(ID = 1:length(grid), geom = grid)
mf_map(grid)
mf_label(grid, var = "ID")
```

Intersection pt / grille

```{r}
inter <- st_intersection(agg, grid)
```

Agrégation par carreau


```{r}
length(inter$ID)
inter$Adresse
length(inter$nb)
agg <- aggregate(inter [ ,c("nb"), drop = T], by = list(inter$ID), sum)
names(agg) <- c("ID", "nb")
jointure <- merge(grid, agg, by= "ID")
mf_choro(jointure, var = "nb")
st_write(jointure, "../data/antenneRelais.gpkg", "densite")
```

