---
title: "API"
author: "B. Maranget"
date: "01/03/2023"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Récup API


https://thinkr.fr/les-api-un-enfer/



# Import

```{r}
library(jsonlite)
library(httr)
library(tesseract)
library(magick)
library(tictoc)
```

https://data.education.gouv.fr/api/records/1.0/search/?dataset=fr-en-effectifs-premier-degre&q=bondy&facet=annee_scolaire&facet=academie&facet=libelle_region_2016&facet=code_region_2016&facet=departement&facet=code_departement&facet=numero_de_l_ecole&facet=type_d_ecole&facet=secteur_d_enseignement&facet=code_postal&facet=localite_acheminement&refine.annee_scolaire=2019-2020

https://data.education.gouv.fr/api/records/1.0/search/?dataset=fr-en-effectifs-premier-degre&q=bondy&facet=numero_de_l_ecole&facet=type_d_ecole&facet=secteur_d_enseignement&refine.annee_scolaire=2019-2020

```{r}
rep <- httr::GET("https://data.education.gouv.fr/api/records/1.0/search/?dataset=fr-en-effectifs-premier-degre&q=bondy&facet=numero_de_l_ecole&facet=type_d_ecole&facet=secteur_d_enseignement&refine.annee_scolaire=2019-2020/")
rep$content
rep2 <- rep$records
rep3 <- rawToChar(rep2)
rep4 <- fromJSON(rep3)
rep4


GET ("https://10.61.0.26/")

```


