---
title: "arbres"
author: "B. Maranget"
date: "11/04/2023"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

comptabiliser les arbres en 2 géométries différentes (ligne et point)



# Environnement


## Librairies


```{r}
library(sf)
library(mapsf)
```


## Chemins


```{r}
chemin <- "C:/Users/bmaranget/Documents/03_SIG/03_03_Data/15_PARCS ET JARDINS/"
chemin2 <- "C:/Users/bmaranget/Documents/03_SIG/03_03_Data/03_SOCLE/"
```



# Comptabiliser les arbres 

## données



```{r}
st_layers(paste0(chemin, "campagneArbre.gpkg"))
arbres <- st_read(paste0(chemin, "arbresbondy1.geojson"))
str(arbres)
table(as.integer(arbres$nbArbres), arbres$statut)

agg <- aggregate(as.integer(arbres$nbArbres), by = list(statut=arbres$statut), sum)
names(agg)[2] <- "nb"
knitr::kable(agg)

write.csv(agg,"../data/nbArbres.csv")
```



# recup alignements d'arbres

```{r}

rue <- st_read(paste0(chemin,"03_SOCLE/rue.gpkg"), "rue2023")
alignement <- read.csv("../data/alignement.csv", fileEncoding = "UTF-8")
chercher <- function (i, col) {
  res <- rue$NOM [grep(alignement$CODE [i], rue [, col])]
  nb <- sapply(res, length)
  ind <- which(nb >1)
  res2 <- lapply(ind, chercher)
  }
res <- chercher(1, "NOM")
res <- lapply(c(1:22), chercher)

# tout ceux qui ont 1 ceux qui ont pl de 1 on distigue avec le type
```

