---
title: "fichiers bd topo"
author: "B. Maranget"
date: "10/09/2021"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

couper bd topo via R plutôt que Qgis
+ imagerie

# Import

```{r}
library(sf)
library(mapsf)
library(units)
```


Chemin

```{r}
chemin <- Sys.getenv("HOME")
```



```{r}
data <- st_read(paste0(chemin,"03_Data/03_SOCLE/BDTOPO_3-3_TOUSTHEMES_SHP_LAMB93_D093_2024-03-15/BDTOPO/1_DONNEES_LIVRAISON_2024-04-00042\BDT_3-3_SHP_LAMB93_D093-ED2024-03-15/BDT_3-0_SHP_LAMB93_D093-ED2021-06-15/TRANSPORT/TRONCON_DE_ROUTE.shp", quiet = T)
limite <- st_read(paste0(chemin,"/03_SIG/03_03_Data/03_SOCLE/limites.gpkg"),"commune", quiet = T)
inter <- st_intersection(data, limite)
st_write(inter,"../../03_Data/03_SOCLE/bondy.gpkg", "routeBDTOPO", quiet = T)
adresse <- st_read("../../03_Data/03_SOCLE/BDTOPO_3-0_TOUSTHEMES_SHP_LAMB93_D093_2021-06-15/BDTOPO/1_DONNEES_LIVRAISON_2021-06-00164/BDT_3-0_SHP_LAMB93_D093-ED2021-06-15/ADRESSES/ADRESSE.shp", quiet = T)
inter <- st_intersection(adresse, limite)
st_write(inter,"../../03_Data/03_SOCLE/bondy.gpkg", "adresseBDTOPO", quiet = T)
```


Exploration package happign

https://paul-carteron.github.io/happign/

```{r}
library(happign)
library(tmap);tmap_mode("plot")
```

```{r}
plot(limite)
commune_borders <- get_wfs(x = limite,
                            layer = "LIMITES_ADMINISTRATIVES_EXPRESS.LATEST:commune")
bondy <- commune_borders [commune_borders$nom == 'Bondy',]
plot(bondy)
class(bondy)
bondy <- bondy$geometry
```




```{r}
metadata <- get_layers_metadata("wmts", "ortho")
ortho_layer <- metadata [1,3]
hr_ortho <- get_wmts(x = bondy,
                     layer = ortho_layer)
tm_shape(hr_ortho) +
   tm_rgb(title = "Orthophoto Hight Resolution") +
tm_shape(bondy)+
   tm_borders(lwd = 2)+
tm_layout(main.title = "Orthophoto Hight Resolution",
          main.title.position = "center",
          legend.position = c("right", "bottom"),
          legend.bg.color = "white", legend.bg.alpha = 0.7)

```

