---
title: "bpe : extraction fichier"
author: "B. Maranget"
date: "11/05/2026"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Pour carte maison de quartier, travail sur BPE 2024 afin d'extraire les établissements ville de Bondy.

# Environnement


## Librairies


```{r}
library(sf)
library(mapsf)
```




# Données

```{r}
bpe <- read.csv2("../data/gros/BPE24.csv", dec = ".")
bpe <- bpe [bpe$CODPOS == 93140 & !is.na(bpe$DOM),]
head(bpe)
# 1920 pt
write.csv(bpe, "../data/bpe2024.csv")
```


```{r}
bpe <- bpe [!is.na(bpe$LAMBERT_X)|!is.na(bpe$LAMBERT_Y),]
# 1918
bpe <- st_as_sf(bpe, coords = c("LAMBERT_X", "LAMBERT_Y"), crs = 2154)
```

1918 pts


codage BPE https://www.insee.fr/fr/metadonnees/source/fichier/BPE24_liste_hierarchisee_TYPEQU.html

champs DOM / SDOM / TYPEQH

3 niveaux : domaine sous domaine type

```{r}
table(bpe$DOM)
```


A services pour les particuliers 

D établissements de santé

E Transports et déplacements

D506 centres sociaux

```{r}
bpe <- bpe [bpe$TYPEQU == "D506",]
```



```{r}
mf_map(bpe)
mf_label(bpe, "NOMRS")
mf_layout("BPE 2024", "BPE 2024\nMai 2026")
```



```{r}
st_write(bpe, "../data/bpe.gpkg", "bpe", delete_layer = T)
```

