---
title: "Cadastre recherche parcelles"
author: "B. Maranget"
date: "3/10/2025"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Recherche parcelles poru enquête terrain


 "code" in ('%J%236%', '%J%318%', '%AT%202%', '%AT%212%')



```{r}
library(sf)
library(mapsf)
```


# Chemin data

Verif cadastre.gpkg

```{r}
couches <- (st_layers("../data/cadastre.gpkg"))
couches <- couches$name
#couches importantes : 1, 9,14
for (i in c(1:length(couches))){
  tmp <- st_read("../data/cadastre.gpkg", couches [i])
  assign(couches [i], tmp)
  st_write(tmp, "../data/cadastreBase.gpkg", couches [i], delete_layer = T)
}
```

# Recherche


```{r}
recherche <- c('J0236', 'J0318', 'AT0202', 'AT0212')
res <- cadastre [cadastre$code %in% recherche,]
st_write(res, "../data/cadastre.gpkg", "res")
```

```{r}
res <- cadastre [grep('^900', cadastre$adresse),]
st_write(res, "../data/cadastre.gpkg", "res9000")
```

