---
title: "Commerces"
author: "B. Maranget"
date: "02/08/2021"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Recodage commerces pour établir cartographie plus simple


# Librairies et répertoire

```{r}
library(sf)
chemin <-  paste0(Sys.getenv('HOME'), "/03_SIG/03_03_Data/")
```


# Données



```{r}
commerce <- st_read("../data/commerces.gpkg","commerces",  quiet = F, stringsAsFactors = F)
tab <- table(commerce$Activité)
categ <- c("alimentation", "loisir", "médical", "service")
write.csv(tab, "../data/categorie.csv")
```


```{r}
categ <- read.csv2("../data/categorie_classe.csv")
jointure <-  merge(commerce, categ, by.x = "Activité", by.y= "Var1")
st_write(jointure [, c("Activité", "categorie", "Freq", "N.", "rue", "Enseigne")], "../data/commerces.gpkg", "jointure", delete_layer = TRUE, quiet = TRUE)
names(jointure)
```

# Cartographie


On fait une carte typologique par catégorie d'enseigne.

```{r}

```


