---
title: "Désherbage comparatif rues"
author: "B. Maranget"
date: "01/03/2023"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

fichier rue sig et fichier rue issu du marché



## Librairies

```{r}
library(sf)
library(mapsf)
```

# data


```{r}
rueSIG <- st_read("D:/03_SIG/03_03_Data/03_SOCLE/socle2024.gpkg", "rues")
rueDes <- read.csv("../data/ruesDesherbage.csv", header = F)
rueDes1 <- read.csv("../data/ruesDesherbage1.csv", header = F)
```

mise en forme rueDes


```{r}
head (rueDes)
data <- rueDes1
num <- seq (1,length(data), by = 3)
eclater <- function (num){
  df <- rueDes [,c(num [1]:(num[1]+2)) ]
}
liste <- lapply(num, eclater)
id <- as.vector( sapply(liste, "[[",1))
type <- as.vector( sapply(liste, "[[",2))
nom <- as.vector( sapply(liste, "[[",3))
df1 <- data.frame(id, type, nom)
df1$desherbage <- "prioritaire"
df$desherbage <- "secondaire"
tot <- rbind(df, df1)
# 328
write.csv(tot, "../data/desherbage.csv", fileEncoding = "UTF-8", row.names = F)
```


```{r}
rueSIG
tot
hamming <- function(i){
  sum(sig != des)
}
sapply()
```

