---
title: "recherche doublons"
author: "B. Maranget"
date: "18/06/2024"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la ç_ç suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

recherche de doublons en général

sous excel supprimer les doublons ou tcd complexe

dans r, plus simple avec duplicated

# Import

```{r}
library(sf)
library(mapsf)
library(units)
```


```{r}
chemin <- paste0(Sys.getenv("HOME"),"/03_SIG/03_03_Data/22_VIDEOSURVEILLANCE/")
fic <- "listeDoublons.csv"
```



```{r}
data <- read.csv2(paste0(chemin, fic), fileEncoding = "UTF-8")
tail(data)
data  <- data [1:128,]
tab <- table(data$coord)
tab <- tab [table(data$coord, useNA = "always") > 1]
sel <- names(tab)

doublons <- data [data$coord %in% sel,]
table(doublons$coord)

doublons

data [order(duplicated(data$coord)),]

sum((duplicated(data$coord)))

data$coord <- paste0(data$LATTITUDE.CAMERA,":", data$LONGITUDE.CAMERA)
data [duplicated(data$coord),]
write.csv(data [duplicated(data$coord), c(1:4,6,7)], "../data/doublons.csv", fileEncoding = "UTF-8")
write.csv(doublons [, c(1:4,6,7)], "../data/doublons2.csv", fileEncoding = "UTF-8")
```

