---
title: "fichiersdvf"
author: "B. Maranget"
date: "10/09/2021"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

couper DVF et jointure avec cadastre


# Import

```{r}
library(sf)
library(mapsf)
library(units)
```


```{r}
dvf <- read.csv("../data/dvf2021s1.txt", sep = "|")
dvfBondy <- dvf [dvf$Commune == "BONDY",]
head(dvfBondy)
cadastre <- st_read("")
limite <- st_read("../../03_Data/limites.gpkg","bondy", quiet = T)
inter <- st_intersection(data, limite)
st_write(inter,"../../03_Data/03_SOCLE/bondy.gpkg", "routeBDTOPO", quiet = T)
adresse <- st_read("../../03_Data/03_SOCLE/BDTOPO_3-0_TOUSTHEMES_SHP_LAMB93_D093_2021-06-15/BDTOPO/1_DONNEES_LIVRAISON_2021-06-00164/BDT_3-0_SHP_LAMB93_D093-ED2021-06-15/ADRESSES/ADRESSE.shp", quiet = T)
inter <- st_intersection(adresse, limite)
st_write(inter,"../../03_Data/03_SOCLE/bondy.gpkg", "adresseBDTOPO", quiet = T)
```

# dvf plus

en avril 2024, exploration des dvf du cerema pour essayer de cerner périmètre ZAC Ourcq


```{r}
bondy <- st_read("../data/limitesSocle.gpkg", "Bondy")
dvf <- st_read("../data/dvf+Bondy.gpkg")
st_layers("../data/limitesSocle.gpkg")
st_layers("../data/pluiM2.gpkg")
zone <- st_read("../data/pluiM2.gpkg", "zone")
ZAC <- zone [zone$LIBELLE == 'UP Bd1',]
mf_map(ZAC)
mf_map(dvf, add = T)
mf_layout("ZAC Ourcq et dvf", "Cerema PLUi M2\navril 2024")
```

Déterminer le prix m2 pour ZAC Ourcq et le reste de Bondy

```{r}
# la ZAC
inter <- st_intersection(dvf, ZAC)
mf_map(inter)
# le reste
zoneReste <- st_difference(bondy, ZAC)
```

