---
title: "PDF carte scolaire"
author: "B. Maranget"
date: "09/05/2022"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Ouverture fichier pdf enseigne pour avoir une base pour les enseignes.


# Import

```{r}
library(pdftools)
library(tidyverse)
library(tesseract)
library(magick)
library(tictoc)
```
Ne pas jouer

```{r, eval = FALSE}
# transformation en image
pngfile <- pdftools::pdf_convert("../data/carteSco.PDF", dpi = 400)
```


```{r, eval = FALSE}
# attention répertoire
path <- dir (pattern = "carteSco",full.names = TRUE)
images <- map(path, magick::image_read)
images [5]
tic()
text_list <- map(images, image_ocr)
toc()
text_list
stext <- unlist(str_split(text_list, "\n"))
tail(stext,50)
```


Le fichier doit être récupérable rapidement
Pour chaque rue (majuscule), il y a des périmètres

l'algo serait :
cherche maj
tant que périmètre, attribue à rue
passe à la maj suivante


```{r}
indRue <- grep("[A-Z]{5,}", stext)
rues <- stext [ind]
indPeri <- grep("Périmétre : ", stext)
peri <- stext [ind]
```

On constitue un df avec la rue et le périmètre en utilisant les indices

```{r}
fairelgRue <- function (ind) {
  nb1 <- indRue [ind]
  nb2 <- indRue [ind+1]
  rep (nb1, (nb2 - nb1) )
} 
lgRue <- fairelgRue(1:359)
Rue <- stext [lgRue]
Peri <- stext [4:1344]
df <- data.frame(Rue, Peri)
head(df)
dfF <- df [grep("Périmétre : ", df$Peri),]
head(dfF)
write.csv(dfF,"../data/peri.csv")
Sellier <- dfF [grep ("Sel", df$Peri),]
Sellier
```



