---
title: "Fibre mairie"
author: "B. Maranget"
date: "06/06/2024"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

jointure doc DSI carto 

chiffrage pour estimation audit



```{r}
library(sf)
library(mapsf)
```


# Chemin data


```{r, eval = T}
# on reprend variable HOME en fonction PC
rep <- Sys.getenv("HOME")
rep2 <- "/03_SIG/03_03_Data/22_VIDEOSURVEILLANCE/" 
rep3 <-  "/03_SIG/03_03_Data/14_CANALISATIONS/ARCEP/"
zip <-  paste0(rep,"/01_ARCHIVE/02_fibre/03_DSI/01_plans/testV5.kmz")
outDir <- paste0(rep, "/01_ARCHIVE/02_fibre/03_DSI/01_plans/")
test <- unzip(outDir, outDir)
```




# données 




```{r}
st_layers("../data/fo.gpkg")
data <- st_read("../data/fo.gpkg", "etat_donnee_fibre_2154")
total <- sum(st_length(data))
# 27 km réseau
agg <- aggregate(data [,"utilisation", drop = F], by= list(data$utilisation, data$importance), length)
agg$longueur <- st_length(agg)
names(agg)[c(1:3)] <- c("valeur donnée", "importance", "nb")
write.csv(st_drop_geometry(agg), "../data/fibre.csv", fileEncoding = "UTF-8", row.names = F)
```

tableau final

On distingue 2 types d'à retrouver / projet / à vérifier et à confirmer

```{r}
agg
```

