---
title: "Recup fichier horodateur Indigo"
author: "B. Maranget"
date: "12/03/2025"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

reprise de données horodateurs indigo pour 2025
les fichiers sont sur 3 onglets excel, on distingue les zones et les types virtuels réels.


```{r}
library(sf)
library(mapsf)
```


# lecture fichier

```{r}
chemin <-  paste0(Sys.getenv('HOME'), "/03_SIG/03_03_Data/08_VOIRIE")
# recup identifiant
virtuel <- read.csv(paste0(chemin, "/indigo/horodateurs2025Virtuel.csv"), dec = ".")
# spatialisation
virtuel <- st_as_sf(virtuel, coords = c("Longitude", "Latitude"), crs = 4326)
horodateur <- st_read("../data/stationnement.gpkg", "horodateurs2024")
horodateur$identifiant <- as.integer(gsub("[^0-9]", "", horodateur$Numéro.horodateur ))
horodateur$type <- "réel"
```


Identifiants

```{r}
nom <- c("num", "adresse", "zone",  "type","identifiant")
virtuel <- virtuel [, c("N..H", "Localisation", "Node")]
virtuel$type <- "virtuel"
virtuel$identifiant <- as.integer(virtuel$N..H)
virtuel
names(virtuel) [c(1:3,5,6)] <- nom
virtuel <- virtuel [, nom]
horodateur <- horodateur [, c("Numéro.horodateur", "adresse", "Node","type", "identifiant")]
names(horodateur) [1:5] <- nom
str(virtuel)
str(horodateur)
names(virtuel) [6] <- "geom"
st_geometry(virtuel) <- "geom"
tot <- rbind(virtuel, horodateur)
```


```{r}
mf_map(tot, type = "typo", var = "type")
st_write(tot, "../data/stationnement.gpkg", "horodateur2025")
```


corrections

```{r}
tot [tot$identifiant == 143,]

```


```{r}
