---
title: "arrêtés de numérotation"
author: "B. Maranget"
date: "09/05/2022"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Ouverture fichier pdf arrêtés pour avoir une base pour les numérotations.


# Import

```{r}
library(pdftools)
library(tidyverse)
library(tesseract)
library(magick)
library(tictoc)
```
Ne pas jouer

```{r, eval = FALSE}
rep <- "../data/numerotation"
file.list <- paste0(rep, "/", list.files(rep, pattern = "*.pdf"))
# transformation en image (utilisation de lapply et fonction intégrée)
lapply(file.list, FUN = function(files) {
  pdftools::pdf_convert(files, format = "jpeg", dpi = 300)
})
```


```{r, eval = FALSE}
# attention répertoire
img.list <- dir (pattern = "jpeg",full.names = TRUE)
images <- map(img.list, magick::image_read)
images
tic()
text_list <- map(images, image_ocr)
toc()
# 15 secondes
text_list
stext <- unlist(str_split(text_list, "\n"))
```


On a une liste de 8 élements, on cherche les éléments suivants

- numéro de l'arrêté (2e lg)
- parcelle concernée (après Section) 
- adresse (3e lg)
- motif de la numérotation (3 lg)


numéro

```{r}
ind <- grep("A2022", stext)
tmp <- stext[ind]
res <- strsplit(tmp, "2022")
resF <- sapply(res, "[",2)
```

parcelle


```{r}
ind <- grep("ection ", stext)
tmp <- stext  [ind]
res <- strsplit(tmp, "n°|N°")
# num parcelle
resF <- sapply(res, "[",2)
resF
parcelle <- unique(as.integer(substr(resF, 1,3))) 
#  section
resF <- sapply(res, "[",1)
tmp <- nchar(resF)
section <- unique(substring(resF, tmp - 2))
```

adresse

```{r}

```

carto

```{r}

library(sf)
st_layers("../data/cadastre.gpkg")
cadastre <- st_read("../data/cadastre.gpkg")
cadastre$codeS <- gsub("0", "",cadastre$code)
paste0(cadastre, parcelle)
# on recherche
cadastre$geom [cadastre$codeS %in% paste0(cadastre, parcelle)]
```


