---
title: "Pdf arrete enseignes"
author: "B. Maranget"
date: "09/05/2022"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Ouverture fichier pdf enseigne pour avoir une base pour les enseignes


# Import

```{r}
library(pdftools)
library(tidyverse)
library(tesseract)
library(magick)
library(tictoc)
```
Ne pas jouer

```{r, eval = FALSE}
# transformation en image
pngfile <- pdftools::pdf_convert("../data/enseigne.PDF", dpi = 400)
```


```{r, eval = FALSE}
# attention répertoire
path <- dir (pattern = "*enseigne",full.names = TRUE)
images <- map(path, magick::image_read)
images
tic()
text_list <- map(images, image_ocr)
toc()
text_list
stext <- unlist(str_split(text_list, "\n"))
```


On a une liste de 3 élements, on veut une seule liste avec seulement les lignes intéresssantes

```{r}
compterMots <- lengths(gregexpr("\\W+", stext)) + 1  
df <- data.frame(stext, compterMots)
df <- df [df$compterMots > 6,] 
df <- df [-1,]
liste <- str_split(df$stext, "[1-9]")
nom <- sapply (liste, "[",1)
```





Comment couper les lignes ? 

```{r, eval = FALSE}
test <- stext [[1]][6]
test
stext <- str_split(test , " AL | R | AV ")
```


On applique des coupures à toutes les chaines, " - ", puis le chiffre



```{r}
# 232 textes 2 exemples
images[1]
(extr <- stext [[1]][1])
# fonctions pour chercher chaine
chercherNum <- function (chaine) {
  lg_num <- grep("[0-9]",chaine, ignore.case = TRUE,value = FALSE)
}
chercherType <- function (chaine) {
  lg_type <- grep("A2021",chaine, ignore.case = TRUE,value = FALSE)
}
vLoc <- c("rue","allée","villa","chemin","avenue","place","voies","Esplanade")
chercherLoc <- function (chaine) {
  lg_loc <- grep(" VL | AL | R | CH | RT | PL | V ",chaine, ignore.case = TRUE,value = FALSE)
}
premiereOccurence <- function(liste) {
  vecteur <-  NULL
  i <- 1
  for (i in 1:length(liste)) {
    tmp <- liste [[i]][1]
    vecteur <- c(vecteur, tmp)
  }
  return(vecteur)
}
liste <- lapply(stext, chercherLoc)
liste
# plusieurs occurences car réf VU
lgType <- premiereOccurence(liste)
# filtrage uniquement sur les vrais arrêtés
ok <- which(!is.na(lgType))
stextSel <- stext [c(ok)]
# 194 vrais arrêtés
# test pour vérifier
liste <- lapply(stextSel, chercherType)
liste
lgType <- premiereOccurence(liste)
length(which(is.na(lgType)))==0
# pas de NA dans la liste des arrêtes
# on cherche les adresses
liste <- lapply(stextSel, chercherLoc)
liste
lgLoc <- premiereOccurence(liste)
pb <- which(is.na(lgLoc))
# pb empty c'est pas de pb
stextSel[c(pb)]
loc <- NULL
i <- 1
for (i in 1:length(stextSel)){
  tmp <- stextSel [[i]][lgLoc[i]]
  loc <- c(loc, tmp)
}
head(loc)
# sauvegarde du résulat
write.csv2(loc, "lieux.csv")
grep("Villa", loc [1], value = TRUE)

locgeo <- geocode(loc, limit = 1, key = "place")

m <- gregexpr("(?i)(?m)(?<=un\\b)(.+)(?=terre\\b)", x, perl=T)
res <- regmatches(x, m)
res <- unlist(res)
res <- gsub("(^ +| +$)", "", res)

res
[1] "mot banni de notre"                            "tremblement de"                               
[3] "mot engendre un mot, une étincelle embrase la"
cat(paste("Ligne", 1:length(res), res, collapse="\n")
    
    
vloc

```

