---
title: "Eclairage public"
author: "B. Maranget"
date: "10/09/2021"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Récupérer les données éclairage public




# Import

Avec R on n'est pas parvenu à lire le dxf. on l'a ouvert avec Qgis et passer en .gpkg


```{r}
library(sf)
library(mapsf)
library(units)
```


```{r}
chemin <- "E:/03_SIG/03_Data"
epEntites <- st_read(paste0(chemin,"/ep.gpkg"), "entites" ,quiet = T)
epPoint <- st_read(paste0(chemin,"/ep.gpkg"), "point" ,quiet = T)
epLigne <- st_read(paste0(chemin,"/ep.gpkg"), "lignes" ,quiet = T)
```

Echantillon sur zone MLK / Blanqui

```{r}
zone <- st_read("../data/prir.gpkg", "limite")
epPointSel <- st_intersection(epPoint, zone)
write_sf(epPointSel, "../data/prir.gpkg", "epPoint", delete_layer = T)
epEntiteSel <- st_intersection(epEntites, zone)
write_sf(epEntiteSel, "../data/prir.gpkg", "epEntites", delete_layer = T)
# pas d'armoire electrique dans la zone
epLigneSel <- st_intersection(epLigne, zone)
write_sf(epLigneSel, "../data/prir.gpkg", "epLigne", delete_layer = T)
```

```{r}
plot(epLigneSel)
plot(epPointSel$geom)
```


```{r}
str(epEntites)
str(epLigneSel)
table(epEntites$Layer)
table(epLigneSel$Layer)
table(epPointSel$Layer)
```

