---
title: "QPV leaflet"
author: "B. Maranget"
date: "01/04/2025"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Créer une carte leaflet qpv pour M. Allen (possibilité de zoom)

```{r}
library(sf)
library(mapsf)
library(leaflet)
```


remarque : bizarre le qpv qui exclue tout le nord de l'av. Jouhaux


# Chemin data


```{r, eval = T}
chemin <-  paste0(Sys.getenv('HOME'), "/03_SIG/03_03_Data/")
```


# Données

reprise des données finales sur le stationnement

```{r}
qpv <- st_read("../data/QP2024_France_hexagonale_LB93.geojson")

st_layers("../data/bondy.gpkg")
bondy <- st_read("../data/bondy.gpkg", "limites")
```

Intersection

```{r}
inter <- st_intersection(qpv, bondy)
inter <- st_transform(inter, 4326)
```



# Carto leaflet




```{r}
leaflet() %>% addTiles(options = tileOptions(minZoom = 10, maxZoom = 20)) %>%
  addPolylines(data=inter, weight = 8 )
```


```{r}
qpv <- st_transform(qpv, 4326)
qpv <- qpv [qpv$insee_dep == 93,] 
qpv <- qpv [grep("Bondy", qpv$lib_com),]
leaflet() %>% addTiles(options = tileOptions(minZoom = 10, maxZoom = 20)) %>%
  addPolylines(data=qpv, weight = 8 )
```

