---
title: "Commerces"
author: "B. Maranget"
date: "02/08/2021"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Recodage commerces pour établir cartographie plus simple


# Librairies et répertoire

```{r}
library(sf)
```

# Données


```{r}
commerce <- st_read("../../03_Data/commerces.gpkg","commerces",  quiet = F, stringsAsFactors = F)
tab <- table(commerce$Activité)
categ <- c("alimentation", "loisir", "médical", "service")
write.csv(tab, "categorie.csv")
```


```{r}
categ <- read.csv2("categorie_classe.csv")
jointure <-  merge(commerce, categ, by.x = "Activité", by.y= "Var1")
st_write(jointure [, c("Activité", "categorie", "Freq", "N.", "rue", "Enseigne")], "../../03_Data/commerces.gpkg", "jointure", delete_layer = TRUE, quiet = TRUE)
names(jointure)
```

Essai de cartogramme de dorling


```{r}

```


