---
title: "Ouverture liste parents rpe"
author: "B. Maranget"
date: "7/07/2021"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Ouverture fichier excel et concaténation de la 4e colonne


# Import

```{r}
library(xlsx)
data <- NA
i <- 1
for (i in 1:20) {
  tmp <- read.xlsx("rpe.xls", startRow=2, header = FALSE,sheetIndex = i, encoding = "UTF-8")
  tmp <- tmp [,c(1,2,6)]
  data <- rbind(data, tmp)
}
names(data) <- c("Nom", "Prenom", "Mail")
```

# Repérer les noms sans adresse mail


```{r}
# lignes vides
fin <- data [!is.na(data$Nom),]
# liste parents sans adresse mail
pasMail <- fin [is.na(fin$Mail)==T,]
# liste parents avec adresse mail
mail <- fin [!is.na(fin$Mail),]
# concaténation des mails
liste <- mail$Mail
fin <- ""
for (i in 1:155) {
  tmp <- paste0(liste [i], ";")
  fin <- paste0(fin, tmp)
}

```




# Export

```{r}
write.csv2(mail, "rpe.csv")
write.csv2(pasMail, "pb.csv")
write(fin, "liste.txt")
```

