---
title: "Numéro de rues - Un sur trois"
author: "B. Maranget"
date: "4/07/2024"
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Affichage des numéros peut poser pb sur les cartes, essai d'afficher 1/3 1/4

extraire les 1er et derniers numéros pour chaque rue et intercaler le coeff désiré

On remarque du coup des doublons chiffres mais pas point. TODO

# Environnement


## Librairies


```{r}
library(sf)
library(mapsf)
```


## Chemins


```{r}
chemin <- "G:/"
```


## Sources

```{r}
st_layers("../data/adresse.gpkg", "ban")
ban <- st_read("../data/adresse.gpkg", "ban")
plot (ban$geom)
```


# sélectionner les numéros par 3




```{r}
ban <- ban [, c("nom_voie", "numero"), drop = F]
# on éclate la ban en liste pour pouvoir gérer les numéros comme des séquences
lban <- split(ban, ban$nom_voie)
# paramètre le tableau car data$numero permet de renvoyer le tableau
choix <- function(data) {
  mini <- min(data$numero)
  # cela fonctionne pour le mini, mais pour le max... nécessité du test
  maxi <- max(data$numero)
  # construction de la série avec seq
  sequence <- seq(mini, maxi, by = 3)
  # filtre sur sequence
  data <- data [data$numero %in% sequence,]
  return(data)
}
choix(data)
liste <- lapply(lban, choix)

# on déroule la liste
nom <- names(sapply(liste, "[[",1))
df <- NULL
for (n in nom){
  l <- liste [n]
  nomRue <- sapply(l, "[[",1)
  num <- sapply(l , "[[",2)
  pt <- sapply(l, "[", 3)
  tmp <- data.frame(nomRue,num, pt)
  names(tmp)[1:2] <- c("nom", "num")
  df <- rbind(df,tmp)
}
st_write(df, "../data/adresse.gpkg", layer = "numerosPar3", delete_layer = T)
```

test de verif pour 3

```{r}
length(ban$id)/length(df$nom)
```

