---
title: "couper fichiers divers réguliers"
author: "B. Maranget"
date: "10/09/2021"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

couper bd topo via R plutôt que Qgis
ban


# Import

```{r}
library(sf)
library(mapsf)
library(units)
```



```{r}
chemin <- "C:/Users/bmaranget/Documents/01_ARCHIVE/01_03_SIG/01_03_03_Data/"
```



```{r}
data <- st_read("../../03_Data/03_SOCLE/BDTOPO_3-0_TOUSTHEMES_SHP_LAMB93_D093_2021-06-15/BDTOPO/1_DONNEES_LIVRAISON_2021-06-00164/BDT_3-0_SHP_LAMB93_D093-ED2021-06-15/TRANSPORT/TRONCON_DE_ROUTE.shp", quiet = T)
limite <- st_read(paste0(chemin,"limites.gpkg"),"bondy", quiet = F)
inter <- st_intersection(data, limite)
st_write(inter,"../../03_Data/03_SOCLE/bondy.gpkg", "routeBDTOPO", quiet = T)
adresse <- st_read("../../03_Data/03_SOCLE/BDTOPO_3-0_TOUSTHEMES_SHP_LAMB93_D093_2021-06-15/BDTOPO/1_DONNEES_LIVRAISON_2021-06-00164/BDT_3-0_SHP_LAMB93_D093-ED2021-06-15/ADRESSES/ADRESSE.shp", quiet = T)
inter <- st_intersection(adresse, limite)
st_write(inter,"../../03_Data/03_SOCLE/bondy.gpkg", "adresseBDTOPO", quiet = T)

```



```{r}
data <- read.csv2("C:/Users/bmaranget/Downloads/adresses-93.csv",fileEncoding = 'UTF-8')
data <- data [data$code_insee == "93010",]
# 8413 adresses
head(data)
adresse <- st_as_sf(data, coords = c("x", "y"), crs = 2154)
st_write(adresse, "../data/adresse.gpkg", "ban", delete_layer = T)
```

