---
title: "Stationnement leaflet"
author: "B. Maranget"
date: "15/07/2024"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```


# Objet

Créer une carte leaflet stationnement

```{r}
library(sf)
library(mapsf)
library(leaflet)
```


# Chemin data


```{r, eval = T}
chemin <-  paste0(Sys.getenv('HOME'), "/03_SIG/03_03_Data/")
```


# Données

reprise des données finales sur le stationnement

```{r}
rue <- st_read("../data/stationnement.gpkg", "rueStationnement2024")
rue <- st_transform(rue, 4326)
```




# Carto leaflet


```{r}
factpal <- colorFactor(c("orange", "green"), rue$couleur)
rue$couleur
```



```{r}
leaflet() %>% addTiles(options = tileOptions(minZoom = 10, maxZoom = 20)) %>%
  addPolylines(data=rue, color = ~factpal(couleur), weight = 8 )
```



```{r}
leaflet()
mf_map(rue)
```

